const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Behaviors.Rotate,
		C3.Plugins.Mouse,
		C3.Behaviors.Orbit,
		C3.Behaviors.Flash,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Plugins.Tilemap,
		C3.Behaviors.Physics,
		C3.Behaviors.destroy,
		C3.Behaviors.wrap,
		C3.Behaviors.Persist,
		C3.Plugins.NinePatch,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Follow,
		C3.Plugins.Arr,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Keyboard.Cnds.OnKeyCodeReleased,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Exps.MaxSpeed,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Orbit.Acts.SetRotation,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Exps.Deceleration,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Platform.Exps.Acceleration,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Behaviors.Rotate.Exps.Acceleration,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Behaviors.Orbit.Acts.SetOffsetAngle,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Orbit.Exps.Speed,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.TiledBg.Cnds.PickParent,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Orbit.Exps.PrimaryRadius,
		C3.Behaviors.Orbit.Exps.SecondaryRadius,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Behaviors.Platform.Acts.ResetDoubleJump,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Behaviors.solid.Acts.SetTags,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Pin.Acts.PinByDistance,
		C3.Behaviors.Pin.Acts.SetPinDistance,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.NinePatch.Cnds.PickParent,
		C3.Plugins.NinePatch.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.NinePatch.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Spritefont2.Acts.MoveAtAngle,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Behaviors.Platform.Exps.MaxFallSpeed,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Behaviors.Orbit.Exps.Rotation,
		C3.Plugins.Tilemap.Acts.SetPos,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Behaviors.Physics.Acts.SetCollisionFilter,
		C3.Plugins.Tilemap.Acts.MoveAtAngle,
		C3.Plugins.Tilemap.Acts.Destroy,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Timer.Cnds.IsTimerPaused,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Bullet.Exps.Acceleration,
		C3.Plugins.Tilemap.Cnds.CompareInstanceVar,
		C3.Plugins.Tilemap.Acts.SetOpacity,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Tilemap.Exps.UID,
		C3.Plugins.Tilemap.Cnds.CompareOpacity,
		C3.Plugins.Spritefont2.Cnds.HasParent,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.System.Exps.len,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetGravityAngle,
		C3.Plugins.Tilemap.Acts.SetVisible,
		C3.Plugins.Tilemap.Acts.SetX,
		C3.Plugins.Tilemap.Cnds.OnCreated,
		C3.Plugins.Particles.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Particles.Exps.Angle
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{TiledBackground: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{PlayerID: 0},
	{jumpKeyCode: 0},
	{leftKeyCode: 0},
	{rightKeyCode: 0},
	{attackKeyCode: 0},
	{specialKeyCode: 0},
	{ControlOverride: 0},
	{shotDelay: 0},
	{Health: 0},
	{maxHealth: 0},
	{bottombartype: 0},
	{specialReload: 0},
	{damageMult: 0},
	{ammo: 0},
	{maxAmmo: 0},
	{reload: 0},
	{lastDamage: 0},
	{damageID: 0},
	{bodyType: 0},
	{intVar1: 0},
	{attackMult: 0},
	{hypnoX: 0},
	{gunner: 0},
	{Pin: 0},
	{gun: 0},
	{DamageType: 0},
	{Damage: 0},
	{Priority: 0},
	{OriginalSpeed: 0},
	{bullet: 0},
	{livesLeft: 0},
	{Timer: 0},
	{healthBar: 0},
	{Tween: 0},
	{Fade: 0},
	{countDown: 0},
	{mirrored: 0},
	{playerSpawner: 0},
	{Sprite3: 0},
	{health: 0},
	{storedSupers: 0},
	{maxSupers: 0},
	{Sprite4: 0},
	{Particles: 0},
	{Rotate: 0},
	{title: 0},
	{Mouse: 0},
	{Orbit: 0},
	{Flash: 0},
	{mode: 0},
	{rightArrow: 0},
	{leftArrow: 0},
	{Type: 0},
	{label: 0},
	{Sprite5: 0},
	{classBanners: 0},
	{Class: 0},
	{Description: 0},
	{hasAlt: 0},
	{type: 0},
	{playerID: 0},
	{selecter: 0},
	{MoveTo: 0},
	{selected: 0},
	{mouseHitbox: 0},
	{largeFont: 0},
	{DragDrop: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{scrollBar: 0},
	{buffer: 0},
	{ScrollTo: 0},
	{Sprite6: 0},
	{exit: 0},
	{randomPick: 0},
	{archer: 0},
	{bow: 0},
	{bullet2: 0},
	{Physics: 0},
	{Tilemap: 0},
	{archerCharge: 0},
	{wizard: 0},
	{wand: 0},
	{DestroyOutsideLayout: 0},
	{fireball: 0},
	{megaFireball: 0},
	{ghost: 0},
	{bottle: 0},
	{ghostBall: 0},
	{storedX: 0},
	{storedY: 0},
	{mirror: 0},
	{Particles2: 0},
	{characterParticle: 0},
	{knight: 0},
	{damage: 0},
	{sword: 0},
	{Strength: 0},
	{durability: 0},
	{maxDurability: 0},
	{shield: 0},
	{shieldBar: 0},
	{shieldMeter: 0},
	{ninja: 0},
	{suriken: 0},
	{surikenBull: 0},
	{Particles3: 0},
	{sniper: 0},
	{gun2: 0},
	{sniperBullet: 0},
	{poof: 0},
	{gambler: 0},
	{cardBull: 0},
	{suriken2: 0},
	{diceBomb: 0},
	{explosion: 0},
	{diceMeter: 0},
	{rubberMan: 0},
	{coconutBull: 0},
	{rubberBall: 0},
	{castawayCharge: 0},
	{steampunk: 0},
	{steampunkPistol: 0},
	{SteamPunkerBullet: 0},
	{farmer: 0},
	{potato: 0},
	{riseKey: 0},
	{fallKey: 0},
	{UnicornPotato: 0},
	{wand2: 0},
	{witch: 0},
	{pumpkin: 0},
	{broom: 0},
	{explosion2: 0},
	{megaPumpkin: 0},
	{robot: 0},
	{lightning: 0},
	{shockBall: 0},
	{grandKnight: 0},
	{sword2: 0},
	{sword3: 0},
	{shield2: 0},
	{golem: 0},
	{rock: 0},
	{runeRock: 0},
	{CEO: 0},
	{goldBall: 0},
	{Wrap: 0},
	{ghostBall2: 0},
	{mechaPunk: 0},
	{clown: 0},
	{beachBall: 0},
	{clownHorn: 0},
	{bullet3: 0},
	{jim: 0},
	{stapler: 0},
	{staple: 0},
	{paper: 0},
	{footballer: 0},
	{chargeHitbox: 0},
	{chargeHitbox2: 0},
	{plantMan: 0},
	{seed: 0},
	{GoTo: 0},
	{Persist: 0},
	{mapIcon: 0},
	{stick: 0},
	{characterName: 0},
	{cactusMan: 0},
	{cactusSeed: 0},
	{cactusWeapon: 0},
	{cactusbomb: 0},
	{demolitioner: 0},
	{dynagun: 0},
	{dynamite: 0},
	{ghostOfTheWest: 0},
	{spiritGun: 0},
	{ghostBullet: 0},
	{dynamiteBundle: 0},
	{Tilemap2: 0},
	{tumbleWeed: 0},
	{tumbleweedSpawner: 0},
	{testDummy: 0},
	{cactusSpawner: 0},
	{gunslinger: 0},
	{gun3: 0},
	{gunslingerPistol: 0},
	{gunslingerSniper: 0},
	{Score: 0},
	{bartender: 0},
	{shotgun: 0},
	{bartenderShotgun: 0},
	{bartenderbottle: 0},
	{confusedEffect: 0},
	{meter: 0},
	{conductor: 0},
	{baton: 0},
	{specialMeter: 0},
	{shieldBar2: 0},
	{trainStart: 0},
	{cart: 0},
	{thief: 0},
	{coin: 0},
	{coinGun: 0},
	{safe: 0},
	{deadEyes: 0},
	{shotgun2: 0},
	{skeletonBullet: 0},
	{grave: 0},
	{headStone: 0},
	{grave2: 0},
	{GhostGunner: 0},
	{GhostGunnerAmmo: 0},
	{cactusking: 0},
	{thorn: 0},
	{loopindex: 0},
	{spikeLand: 0},
	{sword4: 0},
	{shield3: 0},
	{sheriff: 0},
	{sheriffGun: 0},
	{sheriffBullet: 0},
	{lasso: 0},
	{bard: 0},
	{harp: 0},
	{bullet4: 0},
	{loopIndex: 0},
	{musicScore: 0},
	{royalKnight: 0},
	{royalSword: 0},
	{royalShield2: 0},
	{yellEffect: 0},
	{megaFireball2: 0},
	{statue: 0},
	{pillarHammer: 0},
	{anounce: 0},
	{pillar: 0},
	{spikeLand2: 0},
	{elderWizard: 0},
	{wand3: 0},
	{transparentSteamDeckCase: 0},
	{jester: 0},
	{jesterBow: 0},
	{jesterArrow: 0},
	{archerCharge2: 0},
	{smallExplosion: 0},
	{goblin: 0},
	{poisonVile: 0},
	{poisonGoblin: 0},
	{poisonPool: 0},
	{CharacterDescription: 0},
	{lancer: 0},
	{sword5: 0},
	{lancerShield: 0},
	{executioner: 0},
	{executionerAxe: 0},
	{slime: 0},
	{slimeballbull: 0},
	{slimeball: 0},
	{castleTower: 0},
	{"9patch": 0},
	{dragonTamer: 0},
	{shieldBar3: 0},
	{specialMeter2: 0},
	{slimeball2: 0},
	{dragonFireball: 0},
	{Timer2: 0},
	{trainStart2: 0},
	{fireball2: 0},
	{teamRecord1: 0},
	{teamRecord2: 0},
	{cloudMan: 0},
	{cloudBall: 0},
	{waterDroplet: 0},
	{cloud: 0},
	{stormNinja: 0},
	{stormSurikenBull2: 0},
	{stormSuriken: 0},
	{explosion3: 0},
	{pirate: 0},
	{cannon: 0},
	{cannonBall: 0},
	{coralKnight: 0},
	{coralClub: 0},
	{wave: 0},
	{castaway: 0},
	{coconut: 0},
	{coconutBull2: 0},
	{coconutBull3: 0},
	{rubberballBull: 0},
	{rubbermanCharge: 0},
	{ammoLoss: 0},
	{kappa: 0},
	{soul: 0},
	{soulFireball: 0},
	{soulFireball2: 0},
	{swamp: 0},
	{diver: 0},
	{remote: 0},
	{cannonBall2: 0},
	{bigExplosion: 0},
	{radar: 0},
	{fishman: 0},
	{fishPunch: 0},
	{cannonBall3: 0},
	{fish: 0},
	{fishPunch2: 0},
	{octopusCaptain: 0},
	{cannon2: 0},
	{cannonBall4: 0},
	{tentacle: 0},
	{poseidon: 0},
	{trident: 0},
	{fishy: 0},
	{orbitFish: 0},
	{hazmat: 0},
	{remote2: 0},
	{Uranium: 0},
	{radiation: 0},
	{voidNinja: 0},
	{explosion4: 0},
	{Particles4: 0},
	{voidSmokeHitbox: 0},
	{sensei: 0},
	{bamboo: 0},
	{parentX: 0},
	{parentY: 0},
	{teleport: 0},
	{pilot: 0},
	{chargeHitbox3: 0},
	{chargeHitbox4: 0},
	{bomb: 0},
	{bigExplosion2: 0},
	{superSniper: 0},
	{gun4: 0},
	{sniperBullet2: 0},
	{skull1: 0},
	{gun5: 0},
	{necromancer: 0},
	{skull2: 0},
	{voidKnight: 0},
	{voidSword: 0},
	{Pin2: 0},
	{voidSword2: 0},
	{specialForces: 0},
	{suriken3: 0},
	{holyArrow2: 0},
	{specialForcesPortal: 0},
	{surikenBull3: 0},
	{dartFrog: 0},
	{tongue: 0},
	{eskimo: 0},
	{eskimoHammer: 0},
	{coconutBull4: 0},
	{freeze: 0},
	{ice: 0},
	{monk: 0},
	{hand: 0},
	{specialStacks: 0},
	{fishPunch3: 0},
	{alt: 0},
	{fireCracker: 0},
	{cannon3: 0},
	{fireWork: 0},
	{fireCrackerExplosion: 0},
	{rubberballBull2: 0},
	{samurai: 0},
	{samuraiSword: 0},
	{cursedSpirit: 0},
	{gun6: 0},
	{knife: 0},
	{spiritHand: 0},
	{class: 0},
	{Sprite2: 0},
	{TiledBackground2: 0},
	{kunoichi: 0},
	{knife2: 0},
	{knifeHold: 0},
	{spiritKnife: 0},
	{knife3: 0},
	{kunoichiSoul: 0},
	{switch: 0},
	{archerAlt: 0},
	{holyBow: 0},
	{holyArcherCharge: 0},
	{holyArrow: 0},
	{holyArrow3: 0},
	{holyArrow4: 0},
	{merchant: 0},
	{bag: 0},
	{ruby: 0},
	{rubyPickup: 0},
	{djinn: 0},
	{djinnPot: 0},
	{djinnFireball: 0},
	{djinnFireball2: 0},
	{pirate2: 0},
	{hasSkill: 0},
	{spiritHunter: 0},
	{gun7: 0},
	{bullet5: 0},
	{soulRain: 0},
	{spiritPin: 0},
	{megaFireball3: 0},
	{soulBrella: 0},
	{soulBrella2: 0},
	{cannonBall5: 0},
	{index: 0},
	{robotAlt: 0},
	{lazerBolt: 0},
	{TiledBackground3: 0},
	{lazerBolt2: 0},
	{yakuza: 0},
	{gun8: 0},
	{bullet6: 0},
	{briefcase: 0},
	{Platform: 0},
	{yakuzaMinion: 0},
	{ninjaAlt: 0},
	{assasinKnife: 0},
	{mirrorPick: 0},
	{comboMeter: 0},
	{blackbelt: 0},
	{blackBeltPunch: 0},
	{blackBeltPunch2: 0},
	{Bullet: 0},
	{soulFireball3: 0},
	{fly: 0},
	{alien: 0},
	{blaster2: 0},
	{beam: 0},
	{beam2: 0},
	{UFO: 0},
	{log: 0},
	{phase: 0},
	{portalMaster: 0},
	{portalGun: 0},
	{portalBullet: 0},
	{portal: 0},
	{portal2: 0},
	{scavenger: 0},
	{scrapCannon: 0},
	{scrapBall: 0},
	{scrapShard: 0},
	{scrapPile: 0},
	{scrapShard2: 0},
	{settings: 0},
	{togglePowerups: 0},
	{togglePowerups2: 0},
	{powerup: 0},
	{playerSpawner2: 0},
	{label2: 0},
	{togglePowerups3: 0},
	{togglePowerups4: 0},
	{hazmatAlt: 0},
	{rat: 0},
	{plagueRadiation: 0},
	{hazmatAltStaff: 0},
	{ratTrap: 0},
	{sniperGun: 0},
	{sniperRound: 0},
	{sniperAlt: 0},
	{upKeyCode: 0},
	{downKeyCode: 0},
	{Sprite7: 0},
	{sniperExplosion: 0},
	{thiefAlt: 0},
	{coinGun2: 0},
	{coin2: 0},
	{plantManAlt: 0},
	{cactusWeapon2: 0},
	{cactusSeed2: 0},
	{thorn2: 0},
	{spikeLand3: 0},
	{tanglingVines: 0},
	{endScreen: 0},
	{playAgainButton: 0},
	{winText: 0},
	{scientist: 0},
	{stunGun: 0},
	{lightning2: 0},
	{scientistField: 0},
	{slowField: 0},
	{timeSlowEffect: 0},
	{timefastEffect: 0},
	{wanderer: 0},
	{wrench: 0},
	{pointer: 0},
	{wandererCharge: 0},
	{coconutBull5: 0},
	{wrenchBull: 0},
	{glitch: 0},
	{glitchGun: 0},
	{glitchBullet: 0},
	{hack: 0},
	{glitchBullet2: 0},
	{bullet7: 0},
	{poseidonAlt: 0},
	{lightning3: 0},
	{trident2: 0},
	{lightning4: 0},
	{builder: 0},
	{builderWrench: 0},
	{trapMeter: 0},
	{builderBullet: 0},
	{builderBomb: 0},
	{bigExplosion3: 0},
	{builderCannon: 0},
	{cannonBall6: 0},
	{saw: 0},
	{builderPlatform: 0},
	{glue: 0},
	{cannonBall7: 0},
	{headOff: 0},
	{Jumpthru: 0},
	{"9patch2": 0},
	{roboKnight: 0},
	{sword6: 0},
	{lazerSword: 0},
	{builderPlatform2: 0},
	{floorWrap: 0},
	{statueAlt: 0},
	{pillarHammer2: 0},
	{boulder: 0},
	{prototype: 0},
	{gun9: 0},
	{prototypeBullet: 0},
	{enforcer: 0},
	{enforcerGun: 0},
	{enforcerBullet: 0},
	{enforcerBullet2: 0},
	{rot: 0},
	{enforcerBullet3: 0},
	{trapMeter2: 0},
	{witchDoctor: 0},
	{withDoctorWand: 0},
	{witchDoctorFireball: 0},
	{witchDoctorPoison: 0},
	{dartBlower: 0},
	{gun10: 0},
	{dart: 0},
	{poisonDart: 0},
	{stun: 0},
	{fossil: 0},
	{fossilBone: 0},
	{fossilBoneBull: 0},
	{fossilAmber: 0},
	{mosquito: 0},
	{beetle: 0},
	{hunters: 0},
	{bow2: 0},
	{hunterSpear: 0},
	{hunterCharge: 0},
	{DamageID: 0},
	{Follow: 0},
	{hunterBuddy: 0},
	{club: 0},
	{club2: 0},
	{hunterCharge2: 0},
	{sunFollower: 0},
	{sunSplosion: 0},
	{"9patch3": 0},
	{monkAlt: 0},
	{monkAltHand: 0},
	{attackHand: 0},
	{relflectionHand: 0},
	{monkAltHand2: 0},
	{fishmanAlt: 0},
	{fishGun: 0},
	{waterBolt: 0},
	{waterBolt2: 0},
	{specialForcesAlt: 0},
	{suriken4: 0},
	{specialForcesKunai: 0},
	{specialForcesDrone: 0},
	{witchDoctorPoison2: 0},
	{wildMan: 0},
	{sword7: 0},
	{critBar: 0},
	{togglePowerups5: 0},
	{meteor: 0},
	{lava: 0},
	{TiledBackground4: 0},
	{portalTint: 0},
	{upStream: 0},
	{UFOHazard: 0},
	{light: 0},
	{dynastyLantern: 0},
	{Particles5: 0},
	{dragonEgg: 0},
	{trainStart3: 0},
	{water: 0},
	{disableAll: 0},
	{togglePowerups6: 0},
	{togglePowerups7: 0},
	{logMan: 0},
	{shield4: 0},
	{cannon4: 0},
	{acorn: 0},
	{acorn2: 0},
	{dinoTamer: 0},
	{meat: 0},
	{meatBull: 0},
	{meatPickup: 0},
	{pterodactyl: 0},
	{primalFishman: 0},
	{fishPunch4: 0},
	{piranha: 0},
	{ammoGain: 0},
	{builderAlt: 0},
	{partyPopper: 0},
	{balloon: 0},
	{dinoPunch: 0},
	{Sprite8: 0},
	{bardAlt: 0},
	{harp2: 0},
	{bullet8: 0},
	{noteMeter: 0},
	{noteCore: 0},
	{poisonMeter: 0},
	{goblinAlt: 0},
	{poisonVile2: 0},
	{poisonBall: 0},
	{chargeHitbox5: 0},
	{fishPunch5: 0},
	{egg: 0},
	{cheif: 0},
	{boomerang: 0},
	{boomerangBull: 0},
	{boomerang2: 0},
	{djinnAlt: 0},
	{djinnPot2: 0},
	{djinnFireball3: 0},
	{djinnArea: 0},
	{visionEffect: 0},
	{golemAlt: 0},
	{doll: 0},
	{needle: 0},
	{cursedNeedle: 0},
	{voodooDoll: 0},
	{blaster: 0},
	{blasterGun: 0},
	{blasterBullet: 0},
	{blasterMeter: 0},
	{alienAlt: 0},
	{blaster3: 0},
	{beam3: 0},
	{cityBrawler: 0},
	{brawlerFireball: 0},
	{fireballMeter: 0},
	{firePunch: 0},
	{sword8: 0},
	{fireKick: 0},
	{streetArtist: 0},
	{sprayCan: 0},
	{sprayPaint: 0},
	{dynamite2: 0},
	{glove: 0},
	{hopMan: 0},
	{jumpManFireball: 0},
	{fireCrackerExplosion2: 0},
	{powerUpJumpMan: 0},
	{lightning5: 0},
	{fireCrackerExplosion3: 0},
	{spiritBuster: 0},
	{ghostGun: 0},
	{move: 0},
	{bullet9: 0},
	{ghostGoo: 0},
	{wizardAlt: 0},
	{magicianWand: 0},
	{storX: 0},
	{storY: 0},
	{storX2: 0},
	{storY2: 0},
	{magic: 0},
	{hunterBuddy2: 0},
	{stormNinjaAlt: 0},
	{knifeHold2: 0},
	{knife4: 0},
	{stormKunoichiDashBox: 0},
	{glitchAlt: 0},
	{nexus: 0},
	{virusBullet: 0},
	{scientistAlt: 0},
	{soundRemote: 0},
	{lightning6: 0},
	{soundWave: 0},
	{ShotsLeft: 0},
	{tesla: 0},
	{pumpkinBucket: 0},
	{candy: 0},
	{trickOrTreater: 0},
	{healingCandy: 0},
	{scareCrowHand: 0},
	{crow: 0},
	{scareCrow: 0},
	{crow2: 0},
	{stakeGun: 0},
	{stake: 0},
	{vampire: 0},
	{enforcerBullet4: 0},
	{gun11: 0},
	{sandWave: 0},
	{mummy: 0},
	{simitar: 0},
	{sandNado: 0},
	{kingKong: 0},
	{banana: 0},
	{KongPunch: 0},
	{fireballMeter2: 0},
	{godzilla: 0},
	{specialMeter3: 0},
	{shieldBar4: 0},
	{godzillaFireball: 0},
	{godzillaFireball2: 0},
	{pilgrim: 0},
	{cobHold: 0},
	{cob: 0},
	{kernal: 0},
	{pointer2: 0},
	{pong: 0},
	{bullet10: 0},
	{pongBall: 0},
	{pongBall2: 0},
	{togglePowerups8: 0},
	{togglePowerups9: 0},
	{splash: 0},
	{gun12: 0},
	{bell: 0},
	{elf: 0},
	{ring: 0},
	{bigBell: 0},
	{bellField: 0},
	{snowman: 0},
	{snowBallProj: 0},
	{snowball: 0},
	{iceBall: 0},
	{santa: 0},
	{presentProj: 0},
	{present: 0},
	{presentFireball: 0},
	{presentFireball2: 0},
	{sunFollowerAlt: 0},
	{stoneClub: 0},
	{golemShield: 0},
	{cloudManAlt: 0},
	{cloudBall2: 0},
	{smokeCloud: 0},
	{cannonBall8: 0},
	{smashArea: 0},
	{cartoonRabbit: 0},
	{gun13: 0},
	{toonPunch: 0},
	{powHammer: 0},
	{toonMeter: 0},
	{megaFirework: 0},
	{megaFirework2: 0},
	{kunoichiAlt: 0},
	{bow3: 0},
	{bullet11: 0},
	{archerCharge3: 0},
	{spiritArrow: 0},
	{spiritArrow2: 0},
	{ringBull: 0},
	{conic: 0},
	{ringCarry: 0},
	{chargeHitbox6: 0},
	{gun14: 0},
	{bullet12: 0},
	{athena: 0},
	{ringBull2: 0},
	{crit: 0},
	{scrapCannon2: 0},
	{scavengerAlt: 0},
	{turret: 0},
	{nail: 0},
	{megaSparkball: 0},
	{diverAlt: 0},
	{remote3: 0},
	{ring3: 0},
	{blackholeCell: 0},
	{blackHoleRetical: 0},
	{BlackHoleCenter: 0},
	{ring4: 0},
	{healthCounter: 0},
	{sheriffAlt: 0},
	{sheriffGun2: 0},
	{sheriffBullet2: 0},
	{barrel: 0},
	{superBullet: 0},
	{cactusKingThorn: 0},
	{selectionUI: 0},
	{SlotNum: 0},
	{name: 0},
	{description: 0},
	{perkChooser: 0},
	{perkDesc: 0},
	{perkArray: 0},
	{lastShotBullet: 0},
	{perkMine: 0},
	{perkCountDisp: 0},
	{perkInc: 0},
	{perkDec: 0},
	{randomPerk: 0},
	{perkPoisonTrail: 0},
	{hitsLeft: 0},
	{vampireBat: 0},
	{hercules: 0},
	{herculesShield: 0},
	{herculesSword: 0},
	{herculesSword2: 0},
	{parry: 0},
	{ghostAlt: 0},
	{bottle2: 0},
	{ghostBall3: 0},
	{ghostChain: 0},
	{ghostBallSlow: 0},
	{chain: 0},
	{void: 0},
	{void2: 0},
	{voidNinjaAlt: 0},
	{explosion5: 0},
	{samuraiSword2: 0},
	{fireballMeter3: 0},
	{shadowEnergy: 0},
	{anubis: 0},
	{cursedEnergy: 0},
	{anubisStaff: 0},
	{cursedEnergy2: 0},
	{smashArea2: 0},
	{ankh: 0},
	{ankh2: 0},
	{randomChar: 0},
	{wukong: 0},
	{wukongStaff: 0},
	{return: 0},
	{staffWukong: 0},
	{staffWukong2: 0},
	{wukongTeleChecker: 0},
	{superCounter: 0},
	{lokiStaff: 0},
	{faded: 0},
	{lokiBullet: 0},
	{loki: 0},
	{lokiMagicCircle: 0},
	{alternate: 0},
	{hermes: 0},
	{goldenGun: 0},
	{wingBullet: 0},
	{chargeHitbox7: 0},
	{wingBomb: 0},
	{hannya: 0},
	{gun15: 0},
	{leaderBullet: 0},
	{madness: 0},
	{shadowExplosion: 0},
	{leaderBullet2: 0},
	{fossilAlt: 0},
	{cocoon: 0},
	{cocoonProj: 0},
	{maggot: 0},
	{hades: 0},
	{hellSword: 0},
	{flameDagger: 0},
	{hadesRadius: 0},
	{crit2: 0},
	{hellSword2: 0},
	{executionerAxe2: 0},
	{thor: 0},
	{executionerAxe3: 0},
	{executionerAxe4: 0},
	{rubyPickup2: 0},
	{cursedSpiritAlt: 0},
	{charm: 0},
	{gun16: 0},
	{charmEffect: 0},
	{charmKunai: 0},
	{madness2: 0},
	{madness3: 0},
	{gaia: 0},
	{gaiaOrb: 0},
	{healEnergy: 0},
	{attackEnergy: 0},
	{benten: 0},
	{sitar: 0},
	{noteParent: 0},
	{noteChild: 0},
	{noteParent2: 0},
	{noteChild2: 0},
	{camCharge: 0},
	{photographer: 0},
	{camera: 0},
	{cameraFlash: 0},
	{cameraFlash2: 0},
	{dj: 0},
	{boombox: 0},
	{bullet13: 0},
	{missleCount: 0},
	{enforcerAlt: 0},
	{enforcerGun2: 0},
	{enforcerLaser: 0},
	{energyBar: 0},
	{missleCounter: 0},
	{missle: 0},
	{mayor: 0},
	{moneyCase: 0},
	{money: 0},
	{mayorHouse: 0},
	{mayorKey: 0},
	{money2: 0},
	{knife5: 0},
	{dir: 0},
	{wildManAlt: 0},
	{moneyCase2: 0},
	{scratch: 0},
	{octopusCaptainAlt: 0},
	{grimoire: 0},
	{tentaclePortal: 0},
	{tentacleSpear: 0},
	{tentacleSpear2: 0},
	{officer: 0},
	{taser: 0},
	{bolt: 0},
	{shadowEnergy2: 0},
	{handcuff: 0},
	{notepad: 0},
	{superhero: 0},
	{paperAirplane: 0},
	{laser: 0},
	{gun17: 0},
	{superVillain: 0},
	{villainLaser: 0},
	{villainDrone: 0},
	{bullets: 0},
	{villainTurret: 0},
	{twistMode: 0},
	{vigilante: 0},
	{vigilanteCharge: 0},
	{vigilanteStaff: 0},
	{vigilanteStaff2: 0},
	{mines: 0},
	{vigilanteMine: 0},
	{officerAlt: 0},
	{hoseNozzle: 0},
	{waterProj: 0},
	{waterProj2: 0},
	{healthPotion: 0},
	{smashArea3: 0},
	{megasLeft: 0},
	{chef: 0},
	{pan: 0},
	{food: 0},
	{food2: 0},
	{chefFlare: 0},
	{level: 0},
	{critChance: 0},
	{bonusDamage: 0},
	{healUses: 0},
	{rpgHero: 0},
	{rpgHeroSword: 0},
	{upgradeIcon: 0},
	{patriotGun: 0},
	{patriot: 0},
	{miniFirework: 0},
	{miniFirework2: 0},
	{megaFire: 0},
	{spiritBusterAlt: 0},
	{ghostGun2: 0},
	{spiritWave: 0},
	{spiritWave2: 0},
	{slowArea: 0},
	{ghostSlow: 0},
	{elemental: 0},
	{elementalOrb: 0},
	{iceBullet: 0},
	{fireBullet: 0},
	{iceCube: 0},
	{swarmLevel: 0},
	{hivemind: 0},
	{hiveMindGun: 0},
	{hiveMindCore: 0},
	{hiveMindChain: 0},
	{swarmIndicator: 0},
	{smashArea4: 0},
	{weakenEffect: 0},
	{fleetCommander: 0},
	{captainGun: 0},
	{starShot: 0},
	{galaxyStrip: 0},
	{galaxyStrip2: 0},
	{speedZone: 0},
	{speedZonePlace: 0},
	{batter: 0},
	{gun18: 0},
	{baseball: 0},
	{bat: 0},
	{healingCandy2: 0},
	{trooper: 0},
	{trooperBlaster: 0},
	{bullet14: 0},
	{shockGrenade: 0},
	{stunArea: 0},
	{nebula: 0},
	{galaxy: 0},
	{galaxyBall: 0},
	{speedZone2: 0},
	{pumpkinBucket2: 0},
	{trickOrTreaterAlt: 0},
	{spiritPumpkin: 0},
	{healingCandy3: 0},
	{pumpkinSpawn: 0},
	{hannyaAlt: 0},
	{gun19: 0},
	{hannyaAltSpear: 0},
	{angelMeter: 0},
	{Sprite9: 0},
	{hannyaAltSpear2: 0},
	{jimm: 0},
	{stapler2: 0},
	{staple2: 0},
	{witch2: 0},
	{broom2: 0},
	{pumpkin2: 0},
	{slam: 0},
	{sumo: 0},
	{sumoHand: 0},
	{sushiRoll: 0},
	{sushiMeter: 0},
	{futurist: 0},
	{furturistGun: 0},
	{futuristLaser: 0},
	{OrbitalDrone: 0},
	{shouldShoot: 0},
	{Satellite: 0},
	{futuristLaser2: 0},
	{experiment: 0},
	{echoPistol: 0},
	{echo: 0},
	{echoSpawner: 0},
	{energyMeter: 0},
	{monolithSniperShot: 0},
	{pathogen: 0},
	{pathogenGun: 0},
	{virusBall: 0},
	{virusBall2: 0},
	{pathogenVestige: 0},
	{virusBall3: 0},
	{empowered: 0},
	{galacticOutlaw: 0},
	{singularityCapsule: 0},
	{voidWave: 0},
	{voidPortal: 0},
	{cultist: 0},
	{grimoir: 0},
	{cursedVisage: 0},
	{cursedVisage2: 0},
	{sigil: 0},
	{mothMan: 0},
	{gun20: 0},
	{moth: 0},
	{mothBite: 0},
	{lanternMeter: 0},
	{mothLight: 0},
	{hypnotizedEffect: 0},
	{swampCreature: 0},
	{mudHand: 0},
	{angleLaunch: 0},
	{mudBall: 0},
	{mudBall2: 0},
	{phantomKnight: 0},
	{graveBuster: 0},
	{cursedVisage3: 0},
	{wendigo: 0},
	{wendigoStaff: 0},
	{boneShard: 0},
	{curse: 0},
	{boneShard2: 0},
	{cursedVisage4: 0},
	{yukiOnna: 0},
	{gun21: 0},
	{yukiOnnaNote: 0},
	{yukiOnnaNote2: 0},
	{superFreezeEffect: 0},
	{freezeEffect: 0},
	{bellGun: 0},
	{specAmount: 0},
	{vampireAlt: 0},
	{batProjectile: 0},
	{heal: 0},
	{bloodBat: 0},
	{marionette: 0},
	{marionetteCross: 0},
	{eyeball: 0},
	{ring2: 0},
	{babyHead: 0},
	{string: 0},
	{porcelainShard: 0},
	{combo: 0},
	{oni: 0},
	{gun22: 0},
	{bullet15: 0},
	{oniClub: 0},
	{executionerAxe5: 0},
	{cursedVisage5: 0},
	{vx: 0},
	{vy: 0},
	{SPEED: 0},
	{cursedVisage6: 0},
	{yeti: 0},
	{iceCannon: 0},
	{iceballProj: 0},
	{icicle: 0},
	{freezeArea: 0},
	{freezeEffect2: 0},
	{siren: 0},
	{conch: 0},
	{acidDrop: 0},
	{poisonEffect: 0},
	{poisonBar: 0},
	{blowfish: 0},
	{cloudPlatform: 0},
	{healOrb: 0},
	{galaxyTile: 0},
	{frame: 0},
	{mapMove: 0},
	{page: 0},
	{levelController: 0},
	{darkness: 0},
	{madnessDuration: 0},
	{eclipseMeter: 0},
	{isUpdraft: 0},
	{sandstorm: 0},
	{shinobi: 0},
	{kunaiHeld: 0},
	{kunaiBullet: 0},
	{shadowClone: 0},
	{pop: 0},
	{poisonGoblin2: 0},
	{salaryMan: 0},
	{phone: 0},
	{speechBubble: 0},
	{speechBubble2: 0},
	{gun23: 0},
	{bullet16: 0},
	{healOnLeft: 0},
	{idol: 0},
	{microphone: 0},
	{idolNote: 0},
	{idolWave: 0},
	{idolCharmRadius: 0},
	{motivatedEffect: 0},
	{rage: 0},
	{delinquent: 0},
	{gun24: 0},
	{bullet17: 0},
	{nailedBat: 0},
	{hadesRadius2: 0},
	{ora: 0},
	{rageMeter: 0},
	{ora2: 0},
	{foodVendor: 0},
	{skewer: 0},
	{kebab: 0},
	{engorged: 0},
	{takoyaki: 0},
	{sashimi: 0},
	{mascot: 0},
	{dinoPunch2: 0},
	{pacify: 0},
	{pacifyEffect: 0},
	{bugCatcher: 0},
	{bugNet: 0},
	{beetleBullet: 0},
	{bullet18: 0},
	{priest: 0},
	{purificationFlower: 0},
	{charmMiko: 0},
	{priestShieldSegment: 0},
	{sumoWave: 0},
	{karmaArea: 0},
	{weighedEffect: 0},
	{cherryTree: 0},
	{cherryBranch: 0},
	{flowerBall: 0},
	{flowerPetal: 0},
	{flowerBall2: 0},
	{flowerBall3: 0},
	{festivalMan: 0},
	{festivalStick: 0},
	{koiKite: 0},
	{aimingAngle: 0},
	{hypercharged: 0},
	{carpSpawner: 0},
	{blessedBolt: 0},
	{blessedPrism: 0},
	{seraphim: 0},
	{orbitMode: 0},
	{martyr: 0},
	{curvedKnife: 0},
	{bloodyStab: 0},
	{curse2: 0},
	{spiritChains: 0},
	{bleed: 0},
	{knockback: 0},
	{players: 0},
	{weapons: 0},
	{projectiles: 0},
	{bars: 0},
	{melee: 0},
	{shields: 0},
	{builderObjects: 0},
	{Player1Default: 0},
	{playerCount: 0},
	{turn: 0},
	{player1class: 0},
	{player2class: 0},
	{player3class: 0},
	{player4class: 0},
	{score1: 0},
	{score2: 0},
	{score3: 0},
	{score4: 0},
	{teams: 0},
	{started: 0},
	{powerups: 0},
	{lives: 0},
	{zeroDelay: 0},
	{instantReload: 0},
	{meteors: 0},
	{bulletKnockback: 0},
	{worseStageHazards: 0},
	{bigBullets: 0},
	{fastPlayers: 0},
	{player1AttackKey: 0},
	{player2AttackKey: 0},
	{player3AttackKey: 0},
	{player4AttackKey: 0},
	{perkCount: 0},
	{choosingPerkUID: 0},
	{chosenPerk: 0},
	{X: 0},
	{Y: 0},
	{ID: 0},
	{storID: 0},
	{randAng: 0},
	{choice: 0},
	{UID: 0},
	{leftCont: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	gunner: class extends self.ISpriteInstance {},
	gun: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	healthBar: class extends self.ISpriteInstance {},
	countDown: class extends self.ISpriteInstance {},
	playerSpawner: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	health: class extends self.ITiledBackgroundInstance {},
	ammo: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	title: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	mode: class extends self.ISpriteInstance {},
	rightArrow: class extends self.ISpriteInstance {},
	leftArrow: class extends self.ISpriteInstance {},
	label: class extends self.ISpriteFontInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	classBanners: class extends self.ISpriteInstance {},
	selecter: class extends self.ISpriteInstance {},
	selected: class extends self.ISpriteInstance {},
	mouseHitbox: class extends self.ISpriteInstance {},
	largeFont: class extends self.ISpriteFontInstance {},
	scrollBar: class extends self.ISpriteInstance {},
	buffer: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	randomPick: class extends self.ISpriteInstance {},
	archer: class extends self.ISpriteInstance {},
	bow: class extends self.ISpriteInstance {},
	bullet2: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	archerCharge: class extends self.ISpriteInstance {},
	wizard: class extends self.ISpriteInstance {},
	wand: class extends self.ISpriteInstance {},
	fireball: class extends self.ISpriteInstance {},
	megaFireball: class extends self.ISpriteInstance {},
	ghost: class extends self.ISpriteInstance {},
	bottle: class extends self.ISpriteInstance {},
	ghostBall: class extends self.ISpriteInstance {},
	mirror: class extends self.ISpriteInstance {},
	Particles2: class extends self.IParticlesInstance {},
	characterParticle: class extends self.ISpriteInstance {},
	knight: class extends self.ISpriteInstance {},
	sword: class extends self.ISpriteInstance {},
	shield: class extends self.ISpriteInstance {},
	shieldBar: class extends self.ISpriteInstance {},
	shieldMeter: class extends self.ITiledBackgroundInstance {},
	ninja: class extends self.ISpriteInstance {},
	suriken: class extends self.ISpriteInstance {},
	surikenBull: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	sniper: class extends self.ISpriteInstance {},
	gun2: class extends self.ISpriteInstance {},
	sniperBullet: class extends self.ISpriteInstance {},
	poof: class extends self.IParticlesInstance {},
	gambler: class extends self.ISpriteInstance {},
	cardBull: class extends self.ISpriteInstance {},
	suriken2: class extends self.ISpriteInstance {},
	diceBomb: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	diceMeter: class extends self.ISpriteInstance {},
	rubberMan: class extends self.ISpriteInstance {},
	coconutBull: class extends self.ISpriteInstance {},
	rubberBall: class extends self.ISpriteInstance {},
	castawayCharge: class extends self.ISpriteInstance {},
	steampunk: class extends self.ISpriteInstance {},
	steampunkPistol: class extends self.ISpriteInstance {},
	SteamPunkerBullet: class extends self.ISpriteInstance {},
	farmer: class extends self.ISpriteInstance {},
	potato: class extends self.ISpriteInstance {},
	UnicornPotato: class extends self.ISpriteInstance {},
	wand2: class extends self.ISpriteInstance {},
	witch: class extends self.ISpriteInstance {},
	pumpkin: class extends self.ISpriteInstance {},
	broom: class extends self.ISpriteInstance {},
	explosion2: class extends self.ISpriteInstance {},
	megaPumpkin: class extends self.ISpriteInstance {},
	robot: class extends self.ISpriteInstance {},
	lightning: class extends self.ISpriteInstance {},
	shockBall: class extends self.ISpriteInstance {},
	grandKnight: class extends self.ISpriteInstance {},
	sword2: class extends self.ISpriteInstance {},
	sword3: class extends self.ISpriteInstance {},
	shield2: class extends self.ISpriteInstance {},
	golem: class extends self.ISpriteInstance {},
	rock: class extends self.ISpriteInstance {},
	runeRock: class extends self.ISpriteInstance {},
	CEO: class extends self.ISpriteInstance {},
	goldBall: class extends self.ISpriteInstance {},
	ghostBall2: class extends self.ISpriteInstance {},
	mechaPunk: class extends self.ISpriteInstance {},
	clown: class extends self.ISpriteInstance {},
	beachBall: class extends self.ISpriteInstance {},
	clownHorn: class extends self.ISpriteInstance {},
	bullet3: class extends self.ISpriteInstance {},
	jim: class extends self.ISpriteInstance {},
	stapler: class extends self.ISpriteInstance {},
	staple: class extends self.ISpriteInstance {},
	paper: class extends self.ISpriteInstance {},
	footballer: class extends self.ISpriteInstance {},
	chargeHitbox: class extends self.ISpriteInstance {},
	chargeHitbox2: class extends self.ISpriteInstance {},
	plantMan: class extends self.ISpriteInstance {},
	seed: class extends self.ISpriteInstance {},
	mapIcon: class extends self.ISpriteInstance {},
	stick: class extends self.ISpriteInstance {},
	characterName: class extends self.ISpriteFontInstance {},
	cactusMan: class extends self.ISpriteInstance {},
	cactusSeed: class extends self.ISpriteInstance {},
	cactusWeapon: class extends self.ISpriteInstance {},
	cactusbomb: class extends self.ISpriteInstance {},
	demolitioner: class extends self.ISpriteInstance {},
	dynagun: class extends self.ISpriteInstance {},
	dynamite: class extends self.ISpriteInstance {},
	ghostOfTheWest: class extends self.ISpriteInstance {},
	spiritGun: class extends self.ISpriteInstance {},
	ghostBullet: class extends self.ISpriteInstance {},
	dynamiteBundle: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	tumbleWeed: class extends self.ISpriteInstance {},
	tumbleweedSpawner: class extends self.ISpriteInstance {},
	testDummy: class extends self.ISpriteInstance {},
	cactusSpawner: class extends self.ISpriteInstance {},
	gunslinger: class extends self.ISpriteInstance {},
	gun3: class extends self.ISpriteInstance {},
	gunslingerPistol: class extends self.ISpriteInstance {},
	gunslingerSniper: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteFontInstance {},
	bartender: class extends self.ISpriteInstance {},
	shotgun: class extends self.ISpriteInstance {},
	bartenderShotgun: class extends self.ISpriteInstance {},
	bartenderbottle: class extends self.ISpriteInstance {},
	confusedEffect: class extends self.ISpriteInstance {},
	conductor: class extends self.ISpriteInstance {},
	baton: class extends self.ISpriteInstance {},
	specialMeter: class extends self.ITiledBackgroundInstance {},
	shieldBar2: class extends self.ISpriteInstance {},
	trainStart: class extends self.ISpriteInstance {},
	cart: class extends self.ISpriteInstance {},
	thief: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	coinGun: class extends self.ISpriteInstance {},
	safe: class extends self.ISpriteInstance {},
	deadEyes: class extends self.ISpriteInstance {},
	shotgun2: class extends self.ISpriteInstance {},
	skeletonBullet: class extends self.ISpriteInstance {},
	grave: class extends self.ISpriteInstance {},
	headStone: class extends self.ISpriteInstance {},
	grave2: class extends self.ISpriteInstance {},
	GhostGunner: class extends self.ISpriteInstance {},
	GhostGunnerAmmo: class extends self.ISpriteInstance {},
	cactusking: class extends self.ISpriteInstance {},
	thorn: class extends self.ISpriteInstance {},
	spikeLand: class extends self.ISpriteInstance {},
	sword4: class extends self.ISpriteInstance {},
	shield3: class extends self.ISpriteInstance {},
	sheriff: class extends self.ISpriteInstance {},
	sheriffGun: class extends self.ISpriteInstance {},
	sheriffBullet: class extends self.ISpriteInstance {},
	lasso: class extends self.ISpriteInstance {},
	bard: class extends self.ISpriteInstance {},
	harp: class extends self.ISpriteInstance {},
	bullet4: class extends self.ISpriteInstance {},
	musicScore: class extends self.ISpriteInstance {},
	royalKnight: class extends self.ISpriteInstance {},
	royalSword: class extends self.ISpriteInstance {},
	royalShield2: class extends self.ISpriteInstance {},
	yellEffect: class extends self.ISpriteInstance {},
	megaFireball2: class extends self.ISpriteInstance {},
	statue: class extends self.ISpriteInstance {},
	pillarHammer: class extends self.ISpriteInstance {},
	anounce: class extends self.ISpriteInstance {},
	pillar: class extends self.ISpriteInstance {},
	spikeLand2: class extends self.ISpriteInstance {},
	elderWizard: class extends self.ISpriteInstance {},
	wand3: class extends self.ISpriteInstance {},
	transparentSteamDeckCase: class extends self.ISpriteInstance {},
	jester: class extends self.ISpriteInstance {},
	jesterBow: class extends self.ISpriteInstance {},
	jesterArrow: class extends self.ISpriteInstance {},
	archerCharge2: class extends self.ISpriteInstance {},
	smallExplosion: class extends self.ISpriteInstance {},
	goblin: class extends self.ISpriteInstance {},
	poisonVile: class extends self.ISpriteInstance {},
	poisonGoblin: class extends self.ISpriteInstance {},
	poisonPool: class extends self.ISpriteInstance {},
	CharacterDescription: class extends self.ISpriteFontInstance {},
	lancer: class extends self.ISpriteInstance {},
	sword5: class extends self.ISpriteInstance {},
	lancerShield: class extends self.ISpriteInstance {},
	executioner: class extends self.ISpriteInstance {},
	executionerAxe: class extends self.ISpriteInstance {},
	slime: class extends self.ISpriteInstance {},
	slimeballbull: class extends self.ISpriteInstance {},
	slimeball: class extends self.ISpriteInstance {},
	castleTower: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	dragonTamer: class extends self.ISpriteInstance {},
	shieldBar3: class extends self.ISpriteInstance {},
	specialMeter2: class extends self.ITiledBackgroundInstance {},
	slimeball2: class extends self.ISpriteInstance {},
	dragonFireball: class extends self.ISpriteInstance {},
	trainStart2: class extends self.ISpriteInstance {},
	fireball2: class extends self.ISpriteInstance {},
	teamRecord1: class extends self.ISpriteInstance {},
	teamRecord2: class extends self.ISpriteInstance {},
	cloudMan: class extends self.ISpriteInstance {},
	cloudBall: class extends self.ISpriteInstance {},
	waterDroplet: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	stormNinja: class extends self.ISpriteInstance {},
	stormSurikenBull2: class extends self.ISpriteInstance {},
	stormSuriken: class extends self.ISpriteInstance {},
	explosion3: class extends self.ISpriteInstance {},
	pirate: class extends self.ISpriteInstance {},
	cannon: class extends self.ISpriteInstance {},
	cannonBall: class extends self.ISpriteInstance {},
	coralKnight: class extends self.ISpriteInstance {},
	coralClub: class extends self.ISpriteInstance {},
	wave: class extends self.ISpriteInstance {},
	castaway: class extends self.ISpriteInstance {},
	coconut: class extends self.ISpriteInstance {},
	coconutBull2: class extends self.ISpriteInstance {},
	coconutBull3: class extends self.ISpriteInstance {},
	rubberballBull: class extends self.ISpriteInstance {},
	rubbermanCharge: class extends self.ISpriteInstance {},
	ammoLoss: class extends self.ISpriteInstance {},
	kappa: class extends self.ISpriteInstance {},
	soul: class extends self.ISpriteInstance {},
	soulFireball: class extends self.ISpriteInstance {},
	soulFireball2: class extends self.ISpriteInstance {},
	swamp: class extends self.ISpriteInstance {},
	diver: class extends self.ISpriteInstance {},
	remote: class extends self.ISpriteInstance {},
	cannonBall2: class extends self.ISpriteInstance {},
	bigExplosion: class extends self.ISpriteInstance {},
	radar: class extends self.ISpriteInstance {},
	fishman: class extends self.ISpriteInstance {},
	fishPunch: class extends self.ISpriteInstance {},
	cannonBall3: class extends self.ISpriteInstance {},
	fish: class extends self.ISpriteInstance {},
	fishPunch2: class extends self.ISpriteInstance {},
	octopusCaptain: class extends self.ISpriteInstance {},
	cannon2: class extends self.ISpriteInstance {},
	cannonBall4: class extends self.ISpriteInstance {},
	tentacle: class extends self.ISpriteInstance {},
	poseidon: class extends self.ISpriteInstance {},
	trident: class extends self.ISpriteInstance {},
	fishy: class extends self.ISpriteInstance {},
	orbitFish: class extends self.ISpriteInstance {},
	hazmat: class extends self.ISpriteInstance {},
	remote2: class extends self.ISpriteInstance {},
	Uranium: class extends self.ISpriteInstance {},
	radiation: class extends self.ISpriteInstance {},
	damage: class extends self.ISpriteFontInstance {},
	voidNinja: class extends self.ISpriteInstance {},
	explosion4: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	voidSmokeHitbox: class extends self.ISpriteInstance {},
	sensei: class extends self.ISpriteInstance {},
	bamboo: class extends self.ISpriteInstance {},
	teleport: class extends self.ISpriteInstance {},
	pilot: class extends self.ISpriteInstance {},
	chargeHitbox3: class extends self.ISpriteInstance {},
	chargeHitbox4: class extends self.ISpriteInstance {},
	bomb: class extends self.ISpriteInstance {},
	bigExplosion2: class extends self.ISpriteInstance {},
	superSniper: class extends self.ISpriteInstance {},
	gun4: class extends self.ISpriteInstance {},
	sniperBullet2: class extends self.ISpriteInstance {},
	skull1: class extends self.ISpriteInstance {},
	gun5: class extends self.ISpriteInstance {},
	necromancer: class extends self.ISpriteInstance {},
	skull2: class extends self.ISpriteInstance {},
	voidKnight: class extends self.ISpriteInstance {},
	voidSword: class extends self.ISpriteInstance {},
	voidSword2: class extends self.ISpriteInstance {},
	specialForces: class extends self.ISpriteInstance {},
	suriken3: class extends self.ISpriteInstance {},
	holyArrow2: class extends self.ISpriteInstance {},
	specialForcesPortal: class extends self.ISpriteInstance {},
	surikenBull3: class extends self.ISpriteInstance {},
	dartFrog: class extends self.ISpriteInstance {},
	tongue: class extends self.ISpriteInstance {},
	eskimo: class extends self.ISpriteInstance {},
	eskimoHammer: class extends self.ISpriteInstance {},
	coconutBull4: class extends self.ISpriteInstance {},
	freeze: class extends self.ISpriteInstance {},
	ice: class extends self.ISpriteInstance {},
	monk: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	specialStacks: class extends self.ISpriteInstance {},
	fishPunch3: class extends self.ISpriteInstance {},
	fireCracker: class extends self.ISpriteInstance {},
	cannon3: class extends self.ISpriteInstance {},
	fireWork: class extends self.ISpriteInstance {},
	fireCrackerExplosion: class extends self.ISpriteInstance {},
	rubberballBull2: class extends self.ISpriteInstance {},
	samurai: class extends self.ISpriteInstance {},
	samuraiSword: class extends self.ISpriteInstance {},
	cursedSpirit: class extends self.ISpriteInstance {},
	gun6: class extends self.ISpriteInstance {},
	knife: class extends self.ISpriteInstance {},
	spiritHand: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	kunoichi: class extends self.ISpriteInstance {},
	knife2: class extends self.ISpriteInstance {},
	knifeHold: class extends self.ISpriteInstance {},
	spiritKnife: class extends self.ISpriteInstance {},
	knife3: class extends self.ISpriteInstance {},
	kunoichiSoul: class extends self.ISpriteInstance {},
	switch: class extends self.ISpriteInstance {},
	archerAlt: class extends self.ISpriteInstance {},
	holyBow: class extends self.ISpriteInstance {},
	holyArcherCharge: class extends self.ISpriteInstance {},
	holyArrow: class extends self.ISpriteInstance {},
	holyArrow3: class extends self.ISpriteInstance {},
	holyArrow4: class extends self.ISpriteInstance {},
	merchant: class extends self.ISpriteInstance {},
	bag: class extends self.ISpriteInstance {},
	ruby: class extends self.ISpriteInstance {},
	rubyPickup: class extends self.ISpriteInstance {},
	djinn: class extends self.ISpriteInstance {},
	djinnPot: class extends self.ISpriteInstance {},
	djinnFireball: class extends self.ISpriteInstance {},
	djinnFireball2: class extends self.ISpriteInstance {},
	pirate2: class extends self.ISpriteInstance {},
	spiritHunter: class extends self.ISpriteInstance {},
	gun7: class extends self.ISpriteInstance {},
	bullet5: class extends self.ISpriteInstance {},
	soulRain: class extends self.ISpriteInstance {},
	spiritPin: class extends self.ISpriteInstance {},
	megaFireball3: class extends self.ISpriteInstance {},
	soulBrella: class extends self.ISpriteInstance {},
	soulBrella2: class extends self.ISpriteInstance {},
	cannonBall5: class extends self.ISpriteInstance {},
	robotAlt: class extends self.ISpriteInstance {},
	lazerBolt: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	lazerBolt2: class extends self.ISpriteInstance {},
	yakuza: class extends self.ISpriteInstance {},
	gun8: class extends self.ISpriteInstance {},
	bullet6: class extends self.ISpriteInstance {},
	briefcase: class extends self.ISpriteInstance {},
	yakuzaMinion: class extends self.ISpriteInstance {},
	ninjaAlt: class extends self.ISpriteInstance {},
	assasinKnife: class extends self.ISpriteInstance {},
	mirrorPick: class extends self.ISpriteInstance {},
	blackbelt: class extends self.ISpriteInstance {},
	blackBeltPunch: class extends self.ISpriteInstance {},
	blackBeltPunch2: class extends self.ISpriteInstance {},
	comboMeter: class extends self.ISpriteInstance {},
	soulFireball3: class extends self.ISpriteInstance {},
	alien: class extends self.ISpriteInstance {},
	blaster2: class extends self.ISpriteInstance {},
	beam: class extends self.ISpriteInstance {},
	beam2: class extends self.ISpriteInstance {},
	UFO: class extends self.ISpriteInstance {},
	log: class extends self.ISpriteInstance {},
	portalMaster: class extends self.ISpriteInstance {},
	portalGun: class extends self.ISpriteInstance {},
	portalBullet: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	portal2: class extends self.ISpriteInstance {},
	scavenger: class extends self.ISpriteInstance {},
	scrapCannon: class extends self.ISpriteInstance {},
	scrapBall: class extends self.ISpriteInstance {},
	scrapShard: class extends self.ISpriteInstance {},
	scrapPile: class extends self.ISpriteInstance {},
	scrapShard2: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	togglePowerups: class extends self.ISpriteInstance {},
	togglePowerups2: class extends self.ISpriteInstance {},
	powerup: class extends self.ISpriteInstance {},
	playerSpawner2: class extends self.ISpriteInstance {},
	label2: class extends self.ISpriteFontInstance {},
	togglePowerups3: class extends self.ISpriteInstance {},
	togglePowerups4: class extends self.ISpriteInstance {},
	hazmatAlt: class extends self.ISpriteInstance {},
	rat: class extends self.ISpriteInstance {},
	plagueRadiation: class extends self.ISpriteInstance {},
	hazmatAltStaff: class extends self.ISpriteInstance {},
	ratTrap: class extends self.ISpriteInstance {},
	sniperGun: class extends self.ISpriteInstance {},
	sniperRound: class extends self.ISpriteInstance {},
	sniperAlt: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	sniperExplosion: class extends self.ISpriteInstance {},
	thiefAlt: class extends self.ISpriteInstance {},
	coinGun2: class extends self.ISpriteInstance {},
	coin2: class extends self.ISpriteInstance {},
	plantManAlt: class extends self.ISpriteInstance {},
	cactusWeapon2: class extends self.ISpriteInstance {},
	cactusSeed2: class extends self.ISpriteInstance {},
	thorn2: class extends self.ISpriteInstance {},
	spikeLand3: class extends self.ISpriteInstance {},
	tanglingVines: class extends self.ISpriteInstance {},
	endScreen: class extends self.ISpriteInstance {},
	playAgainButton: class extends self.ISpriteInstance {},
	winText: class extends self.ISpriteInstance {},
	scientist: class extends self.ISpriteInstance {},
	stunGun: class extends self.ISpriteInstance {},
	lightning2: class extends self.ISpriteInstance {},
	scientistField: class extends self.ISpriteInstance {},
	slowField: class extends self.ISpriteInstance {},
	timeSlowEffect: class extends self.ISpriteInstance {},
	timefastEffect: class extends self.ISpriteInstance {},
	wanderer: class extends self.ISpriteInstance {},
	wrench: class extends self.ISpriteInstance {},
	pointer: class extends self.ISpriteInstance {},
	wandererCharge: class extends self.ISpriteInstance {},
	coconutBull5: class extends self.ISpriteInstance {},
	wrenchBull: class extends self.ISpriteInstance {},
	glitch: class extends self.ISpriteInstance {},
	glitchGun: class extends self.ISpriteInstance {},
	glitchBullet: class extends self.ISpriteInstance {},
	hack: class extends self.ISpriteInstance {},
	glitchBullet2: class extends self.ISpriteInstance {},
	bullet7: class extends self.ISpriteInstance {},
	poseidonAlt: class extends self.ISpriteInstance {},
	lightning3: class extends self.ISpriteInstance {},
	trident2: class extends self.ISpriteInstance {},
	lightning4: class extends self.ISpriteInstance {},
	builder: class extends self.ISpriteInstance {},
	builderWrench: class extends self.ISpriteInstance {},
	trapMeter: class extends self.ISpriteInstance {},
	builderBullet: class extends self.ISpriteInstance {},
	builderBomb: class extends self.ISpriteInstance {},
	bigExplosion3: class extends self.ISpriteInstance {},
	builderCannon: class extends self.ISpriteInstance {},
	cannonBall6: class extends self.ISpriteInstance {},
	saw: class extends self.ISpriteInstance {},
	builderPlatform: class extends self.ISpriteInstance {},
	glue: class extends self.ISpriteInstance {},
	cannonBall7: class extends self.ISpriteInstance {},
	headOff: class extends self.ISpriteInstance {},
	_9patch2: class extends self.I9PatchInstance {},
	roboKnight: class extends self.ISpriteInstance {},
	sword6: class extends self.ISpriteInstance {},
	lazerSword: class extends self.ISpriteInstance {},
	builderPlatform2: class extends self.ISpriteInstance {},
	floorWrap: class extends self.ITiledBackgroundInstance {},
	statueAlt: class extends self.ISpriteInstance {},
	pillarHammer2: class extends self.ISpriteInstance {},
	boulder: class extends self.ISpriteInstance {},
	prototype: class extends self.ISpriteInstance {},
	gun9: class extends self.ISpriteInstance {},
	prototypeBullet: class extends self.ISpriteInstance {},
	enforcer: class extends self.ISpriteInstance {},
	enforcerGun: class extends self.ISpriteInstance {},
	enforcerBullet: class extends self.ISpriteInstance {},
	enforcerBullet2: class extends self.ISpriteInstance {},
	enforcerBullet3: class extends self.ISpriteInstance {},
	trapMeter2: class extends self.ISpriteInstance {},
	witchDoctor: class extends self.ISpriteInstance {},
	withDoctorWand: class extends self.ISpriteInstance {},
	witchDoctorFireball: class extends self.ISpriteInstance {},
	witchDoctorPoison: class extends self.ISpriteInstance {},
	dartBlower: class extends self.ISpriteInstance {},
	gun10: class extends self.ISpriteInstance {},
	dart: class extends self.ISpriteInstance {},
	poisonDart: class extends self.ISpriteInstance {},
	stun: class extends self.IParticlesInstance {},
	fossil: class extends self.ISpriteInstance {},
	fossilBone: class extends self.ISpriteInstance {},
	fossilBoneBull: class extends self.ISpriteInstance {},
	fossilAmber: class extends self.ISpriteInstance {},
	mosquito: class extends self.ISpriteInstance {},
	beetle: class extends self.ISpriteInstance {},
	hunters: class extends self.ISpriteInstance {},
	bow2: class extends self.ISpriteInstance {},
	hunterSpear: class extends self.ISpriteInstance {},
	hunterCharge: class extends self.ISpriteInstance {},
	hunterBuddy: class extends self.ISpriteInstance {},
	club: class extends self.ISpriteInstance {},
	club2: class extends self.ISpriteInstance {},
	hunterCharge2: class extends self.ISpriteInstance {},
	sunFollower: class extends self.ISpriteInstance {},
	sunSplosion: class extends self.ISpriteInstance {},
	_9patch3: class extends self.I9PatchInstance {},
	monkAlt: class extends self.ISpriteInstance {},
	monkAltHand: class extends self.ISpriteInstance {},
	attackHand: class extends self.ISpriteInstance {},
	relflectionHand: class extends self.ISpriteInstance {},
	monkAltHand2: class extends self.ISpriteInstance {},
	fishmanAlt: class extends self.ISpriteInstance {},
	fishGun: class extends self.ISpriteInstance {},
	waterBolt: class extends self.ISpriteInstance {},
	waterBolt2: class extends self.ISpriteInstance {},
	specialForcesAlt: class extends self.ISpriteInstance {},
	suriken4: class extends self.ISpriteInstance {},
	specialForcesKunai: class extends self.ISpriteInstance {},
	specialForcesDrone: class extends self.ISpriteInstance {},
	witchDoctorPoison2: class extends self.ISpriteInstance {},
	wildMan: class extends self.ISpriteInstance {},
	sword7: class extends self.ISpriteInstance {},
	critBar: class extends self.ISpriteInstance {},
	togglePowerups5: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	lava: class extends self.I9PatchInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	portalTint: class extends self.ITiledBackgroundInstance {},
	upStream: class extends self.ITiledBackgroundInstance {},
	UFOHazard: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	dynastyLantern: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	dragonEgg: class extends self.ISpriteInstance {},
	trainStart3: class extends self.ISpriteInstance {},
	water: class extends self.I9PatchInstance {},
	disableAll: class extends self.ISpriteInstance {},
	togglePowerups6: class extends self.ISpriteInstance {},
	togglePowerups7: class extends self.ISpriteInstance {},
	logMan: class extends self.ISpriteInstance {},
	shield4: class extends self.ISpriteInstance {},
	cannon4: class extends self.ISpriteInstance {},
	acorn: class extends self.ISpriteInstance {},
	acorn2: class extends self.ISpriteInstance {},
	dinoTamer: class extends self.ISpriteInstance {},
	meat: class extends self.ISpriteInstance {},
	meatBull: class extends self.ISpriteInstance {},
	meatPickup: class extends self.ISpriteInstance {},
	pterodactyl: class extends self.ISpriteInstance {},
	primalFishman: class extends self.ISpriteInstance {},
	fishPunch4: class extends self.ISpriteInstance {},
	piranha: class extends self.ISpriteInstance {},
	ammoGain: class extends self.ISpriteInstance {},
	builderAlt: class extends self.ISpriteInstance {},
	partyPopper: class extends self.ISpriteInstance {},
	balloon: class extends self.ISpriteInstance {},
	dinoPunch: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	bardAlt: class extends self.ISpriteInstance {},
	harp2: class extends self.ISpriteInstance {},
	bullet8: class extends self.ISpriteInstance {},
	noteMeter: class extends self.ISpriteInstance {},
	noteCore: class extends self.ISpriteInstance {},
	poisonMeter: class extends self.ISpriteInstance {},
	goblinAlt: class extends self.ISpriteInstance {},
	poisonVile2: class extends self.ISpriteInstance {},
	poisonBall: class extends self.ISpriteInstance {},
	chargeHitbox5: class extends self.ISpriteInstance {},
	fishPunch5: class extends self.ISpriteInstance {},
	egg: class extends self.ISpriteInstance {},
	cheif: class extends self.ISpriteInstance {},
	boomerang: class extends self.ISpriteInstance {},
	boomerangBull: class extends self.ISpriteInstance {},
	boomerang2: class extends self.ISpriteInstance {},
	djinnAlt: class extends self.ISpriteInstance {},
	djinnPot2: class extends self.ISpriteInstance {},
	djinnFireball3: class extends self.ISpriteInstance {},
	djinnArea: class extends self.ISpriteInstance {},
	visionEffect: class extends self.ISpriteInstance {},
	golemAlt: class extends self.ISpriteInstance {},
	doll: class extends self.ISpriteInstance {},
	needle: class extends self.ISpriteInstance {},
	cursedNeedle: class extends self.ISpriteInstance {},
	voodooDoll: class extends self.ISpriteInstance {},
	blaster: class extends self.ISpriteInstance {},
	blasterGun: class extends self.ISpriteInstance {},
	blasterBullet: class extends self.ISpriteInstance {},
	blasterMeter: class extends self.ISpriteInstance {},
	alienAlt: class extends self.ISpriteInstance {},
	blaster3: class extends self.ISpriteInstance {},
	beam3: class extends self.ISpriteInstance {},
	cityBrawler: class extends self.ISpriteInstance {},
	brawlerFireball: class extends self.ISpriteInstance {},
	fireballMeter: class extends self.ISpriteInstance {},
	firePunch: class extends self.ISpriteInstance {},
	sword8: class extends self.ISpriteInstance {},
	fireKick: class extends self.ISpriteInstance {},
	streetArtist: class extends self.ISpriteInstance {},
	sprayCan: class extends self.ISpriteInstance {},
	sprayPaint: class extends self.ISpriteInstance {},
	dynamite2: class extends self.ISpriteInstance {},
	glove: class extends self.ISpriteInstance {},
	hopMan: class extends self.ISpriteInstance {},
	jumpManFireball: class extends self.ISpriteInstance {},
	fireCrackerExplosion2: class extends self.ISpriteInstance {},
	powerUpJumpMan: class extends self.ISpriteInstance {},
	lightning5: class extends self.ISpriteInstance {},
	fireCrackerExplosion3: class extends self.ISpriteInstance {},
	spiritBuster: class extends self.ISpriteInstance {},
	ghostGun: class extends self.ISpriteInstance {},
	bullet9: class extends self.ISpriteInstance {},
	ghostGoo: class extends self.ISpriteInstance {},
	wizardAlt: class extends self.ISpriteInstance {},
	magicianWand: class extends self.ISpriteInstance {},
	magic: class extends self.ISpriteInstance {},
	hunterBuddy2: class extends self.ISpriteInstance {},
	stormNinjaAlt: class extends self.ISpriteInstance {},
	knifeHold2: class extends self.ISpriteInstance {},
	knife4: class extends self.ISpriteInstance {},
	stormKunoichiDashBox: class extends self.ISpriteInstance {},
	glitchAlt: class extends self.ISpriteInstance {},
	nexus: class extends self.ISpriteInstance {},
	virusBullet: class extends self.ISpriteInstance {},
	scientistAlt: class extends self.ISpriteInstance {},
	soundRemote: class extends self.ISpriteInstance {},
	lightning6: class extends self.ISpriteInstance {},
	soundWave: class extends self.ISpriteInstance {},
	tesla: class extends self.ISpriteInstance {},
	pumpkinBucket: class extends self.ISpriteInstance {},
	candy: class extends self.ISpriteInstance {},
	trickOrTreater: class extends self.ISpriteInstance {},
	healingCandy: class extends self.ISpriteInstance {},
	scareCrowHand: class extends self.ISpriteInstance {},
	crow: class extends self.ISpriteInstance {},
	scareCrow: class extends self.ISpriteInstance {},
	crow2: class extends self.ISpriteInstance {},
	stakeGun: class extends self.ISpriteInstance {},
	stake: class extends self.ISpriteInstance {},
	vampire: class extends self.ISpriteInstance {},
	enforcerBullet4: class extends self.ISpriteInstance {},
	gun11: class extends self.ISpriteInstance {},
	sandWave: class extends self.ISpriteInstance {},
	mummy: class extends self.ISpriteInstance {},
	simitar: class extends self.ISpriteInstance {},
	sandNado: class extends self.ISpriteInstance {},
	kingKong: class extends self.ISpriteInstance {},
	banana: class extends self.ISpriteInstance {},
	KongPunch: class extends self.ISpriteInstance {},
	fireballMeter2: class extends self.ISpriteInstance {},
	godzilla: class extends self.ISpriteInstance {},
	specialMeter3: class extends self.ITiledBackgroundInstance {},
	shieldBar4: class extends self.ISpriteInstance {},
	godzillaFireball: class extends self.ISpriteInstance {},
	godzillaFireball2: class extends self.ISpriteInstance {},
	pilgrim: class extends self.ISpriteInstance {},
	cobHold: class extends self.ISpriteInstance {},
	cob: class extends self.ISpriteInstance {},
	kernal: class extends self.ISpriteInstance {},
	pointer2: class extends self.ISpriteInstance {},
	pong: class extends self.ISpriteInstance {},
	bullet10: class extends self.ISpriteInstance {},
	pongBall: class extends self.ISpriteInstance {},
	pongBall2: class extends self.ISpriteInstance {},
	togglePowerups8: class extends self.ISpriteInstance {},
	togglePowerups9: class extends self.ISpriteInstance {},
	splash: class extends self.ISpriteInstance {},
	gun12: class extends self.ISpriteInstance {},
	bell: class extends self.ISpriteInstance {},
	elf: class extends self.ISpriteInstance {},
	ring: class extends self.ISpriteInstance {},
	bigBell: class extends self.ISpriteInstance {},
	bellField: class extends self.ISpriteInstance {},
	snowman: class extends self.ISpriteInstance {},
	snowBallProj: class extends self.ISpriteInstance {},
	snowball: class extends self.ISpriteInstance {},
	iceBall: class extends self.ISpriteInstance {},
	santa: class extends self.ISpriteInstance {},
	presentProj: class extends self.ISpriteInstance {},
	present: class extends self.ISpriteInstance {},
	presentFireball: class extends self.ISpriteInstance {},
	presentFireball2: class extends self.ISpriteInstance {},
	sunFollowerAlt: class extends self.ISpriteInstance {},
	stoneClub: class extends self.ISpriteInstance {},
	golemShield: class extends self.ISpriteInstance {},
	cloudManAlt: class extends self.ISpriteInstance {},
	cloudBall2: class extends self.ISpriteInstance {},
	smokeCloud: class extends self.ISpriteInstance {},
	cannonBall8: class extends self.ISpriteInstance {},
	smashArea: class extends self.ISpriteInstance {},
	cartoonRabbit: class extends self.ISpriteInstance {},
	gun13: class extends self.ISpriteInstance {},
	toonPunch: class extends self.ISpriteInstance {},
	powHammer: class extends self.ISpriteInstance {},
	toonMeter: class extends self.ISpriteInstance {},
	megaFirework: class extends self.ISpriteInstance {},
	megaFirework2: class extends self.ISpriteInstance {},
	kunoichiAlt: class extends self.ISpriteInstance {},
	bow3: class extends self.ISpriteInstance {},
	bullet11: class extends self.ISpriteInstance {},
	archerCharge3: class extends self.ISpriteInstance {},
	spiritArrow: class extends self.ISpriteInstance {},
	spiritArrow2: class extends self.ISpriteInstance {},
	ringBull: class extends self.ISpriteInstance {},
	conic: class extends self.ISpriteInstance {},
	ringCarry: class extends self.ISpriteInstance {},
	chargeHitbox6: class extends self.ISpriteInstance {},
	gun14: class extends self.ISpriteInstance {},
	bullet12: class extends self.ISpriteInstance {},
	athena: class extends self.ISpriteInstance {},
	ringBull2: class extends self.ISpriteInstance {},
	crit: class extends self.ISpriteInstance {},
	scrapCannon2: class extends self.ISpriteInstance {},
	scavengerAlt: class extends self.ISpriteInstance {},
	turret: class extends self.ISpriteInstance {},
	nail: class extends self.ISpriteInstance {},
	megaSparkball: class extends self.ISpriteInstance {},
	diverAlt: class extends self.ISpriteInstance {},
	remote3: class extends self.ISpriteInstance {},
	ring3: class extends self.ISpriteInstance {},
	blackholeCell: class extends self.ISpriteInstance {},
	blackHoleRetical: class extends self.ISpriteInstance {},
	BlackHoleCenter: class extends self.ISpriteInstance {},
	ring4: class extends self.ISpriteInstance {},
	healthCounter: class extends self.ISpriteFontInstance {},
	sheriffAlt: class extends self.ISpriteInstance {},
	sheriffGun2: class extends self.ISpriteInstance {},
	sheriffBullet2: class extends self.ISpriteInstance {},
	barrel: class extends self.ISpriteInstance {},
	superBullet: class extends self.ISpriteInstance {},
	cactusKingThorn: class extends self.ISpriteInstance {},
	selectionUI: class extends self.ISpriteInstance {},
	perkChooser: class extends self.ISpriteInstance {},
	perkDesc: class extends self.ISpriteFontInstance {},
	perkArray: class extends self.IArrayInstance {},
	lastShotBullet: class extends self.ISpriteInstance {},
	perkMine: class extends self.ISpriteInstance {},
	perkCountDisp: class extends self.ISpriteFontInstance {},
	perkInc: class extends self.ISpriteInstance {},
	perkDec: class extends self.ISpriteInstance {},
	randomPerk: class extends self.ISpriteInstance {},
	perkPoisonTrail: class extends self.ISpriteInstance {},
	vampireBat: class extends self.ISpriteInstance {},
	hercules: class extends self.ISpriteInstance {},
	herculesShield: class extends self.ISpriteInstance {},
	herculesSword: class extends self.ISpriteInstance {},
	herculesSword2: class extends self.ISpriteInstance {},
	parry: class extends self.ISpriteInstance {},
	ghostAlt: class extends self.ISpriteInstance {},
	bottle2: class extends self.ISpriteInstance {},
	ghostBall3: class extends self.ISpriteInstance {},
	ghostChain: class extends self.ISpriteInstance {},
	ghostBallSlow: class extends self.ISpriteInstance {},
	chain: class extends self.ITiledBackgroundInstance {},
	void: class extends self.ISpriteInstance {},
	void2: class extends self.ISpriteInstance {},
	voidNinjaAlt: class extends self.ISpriteInstance {},
	explosion5: class extends self.ISpriteInstance {},
	samuraiSword2: class extends self.ISpriteInstance {},
	fireballMeter3: class extends self.ISpriteInstance {},
	shadowEnergy: class extends self.ISpriteInstance {},
	anubis: class extends self.ISpriteInstance {},
	cursedEnergy: class extends self.ISpriteInstance {},
	anubisStaff: class extends self.ISpriteInstance {},
	cursedEnergy2: class extends self.ISpriteInstance {},
	smashArea2: class extends self.ISpriteInstance {},
	ankh: class extends self.ISpriteInstance {},
	ankh2: class extends self.ISpriteInstance {},
	randomChar: class extends self.ISpriteInstance {},
	wukong: class extends self.ISpriteInstance {},
	wukongStaff: class extends self.ISpriteInstance {},
	staffWukong: class extends self.I9PatchInstance {},
	staffWukong2: class extends self.I9PatchInstance {},
	wukongTeleChecker: class extends self.ISpriteInstance {},
	superCounter: class extends self.ISpriteFontInstance {},
	lokiStaff: class extends self.ISpriteInstance {},
	lokiBullet: class extends self.ISpriteInstance {},
	loki: class extends self.ISpriteInstance {},
	lokiMagicCircle: class extends self.ISpriteInstance {},
	hermes: class extends self.ISpriteInstance {},
	goldenGun: class extends self.ISpriteInstance {},
	wingBullet: class extends self.ISpriteInstance {},
	chargeHitbox7: class extends self.ISpriteInstance {},
	wingBomb: class extends self.ISpriteInstance {},
	hannya: class extends self.ISpriteInstance {},
	gun15: class extends self.ISpriteInstance {},
	leaderBullet: class extends self.ISpriteInstance {},
	madness: class extends self.ISpriteInstance {},
	shadowExplosion: class extends self.ISpriteInstance {},
	leaderBullet2: class extends self.ISpriteInstance {},
	fossilAlt: class extends self.ISpriteInstance {},
	cocoon: class extends self.ISpriteInstance {},
	cocoonProj: class extends self.ISpriteInstance {},
	maggot: class extends self.ISpriteInstance {},
	hades: class extends self.ISpriteInstance {},
	hellSword: class extends self.ISpriteInstance {},
	flameDagger: class extends self.ISpriteInstance {},
	hadesRadius: class extends self.ISpriteInstance {},
	crit2: class extends self.ISpriteInstance {},
	hellSword2: class extends self.ISpriteInstance {},
	executionerAxe2: class extends self.ISpriteInstance {},
	thor: class extends self.ISpriteInstance {},
	executionerAxe3: class extends self.ISpriteInstance {},
	executionerAxe4: class extends self.ISpriteInstance {},
	rubyPickup2: class extends self.ISpriteInstance {},
	cursedSpiritAlt: class extends self.ISpriteInstance {},
	charm: class extends self.ISpriteInstance {},
	gun16: class extends self.ISpriteInstance {},
	charmEffect: class extends self.ISpriteInstance {},
	charmKunai: class extends self.ISpriteInstance {},
	madness2: class extends self.ISpriteInstance {},
	madness3: class extends self.ISpriteInstance {},
	gaia: class extends self.ISpriteInstance {},
	gaiaOrb: class extends self.ISpriteInstance {},
	healEnergy: class extends self.ISpriteInstance {},
	attackEnergy: class extends self.ISpriteInstance {},
	benten: class extends self.ISpriteInstance {},
	sitar: class extends self.ISpriteInstance {},
	noteParent: class extends self.ISpriteInstance {},
	noteChild: class extends self.ISpriteInstance {},
	noteParent2: class extends self.ISpriteInstance {},
	noteChild2: class extends self.ISpriteInstance {},
	photographer: class extends self.ISpriteInstance {},
	camera: class extends self.ISpriteInstance {},
	cameraFlash: class extends self.ISpriteInstance {},
	cameraFlash2: class extends self.ISpriteInstance {},
	dj: class extends self.ISpriteInstance {},
	boombox: class extends self.ISpriteInstance {},
	bullet13: class extends self.ISpriteInstance {},
	enforcerAlt: class extends self.ISpriteInstance {},
	enforcerGun2: class extends self.ISpriteInstance {},
	enforcerLaser: class extends self.ISpriteInstance {},
	energyBar: class extends self.ISpriteInstance {},
	missleCounter: class extends self.ISpriteFontInstance {},
	missle: class extends self.ISpriteInstance {},
	mayor: class extends self.ISpriteInstance {},
	moneyCase: class extends self.ISpriteInstance {},
	money: class extends self.ISpriteInstance {},
	mayorHouse: class extends self.ISpriteInstance {},
	mayorKey: class extends self.ISpriteInstance {},
	money2: class extends self.ISpriteInstance {},
	knife5: class extends self.ISpriteInstance {},
	wildManAlt: class extends self.ISpriteInstance {},
	moneyCase2: class extends self.ISpriteInstance {},
	scratch: class extends self.ISpriteInstance {},
	octopusCaptainAlt: class extends self.ISpriteInstance {},
	grimoire: class extends self.ISpriteInstance {},
	tentaclePortal: class extends self.ISpriteInstance {},
	tentacleSpear: class extends self.I9PatchInstance {},
	tentacleSpear2: class extends self.I9PatchInstance {},
	officer: class extends self.ISpriteInstance {},
	taser: class extends self.ISpriteInstance {},
	bolt: class extends self.ISpriteInstance {},
	shadowEnergy2: class extends self.ISpriteInstance {},
	handcuff: class extends self.ISpriteInstance {},
	notepad: class extends self.ISpriteInstance {},
	superhero: class extends self.ISpriteInstance {},
	paperAirplane: class extends self.ISpriteInstance {},
	laser: class extends self.ISpriteInstance {},
	gun17: class extends self.ISpriteInstance {},
	superVillain: class extends self.ISpriteInstance {},
	villainLaser: class extends self.ISpriteInstance {},
	villainDrone: class extends self.ISpriteInstance {},
	villainTurret: class extends self.ISpriteInstance {},
	vigilante: class extends self.ISpriteInstance {},
	vigilanteCharge: class extends self.ISpriteInstance {},
	vigilanteStaff: class extends self.ISpriteInstance {},
	vigilanteStaff2: class extends self.ISpriteInstance {},
	mines: class extends self.ISpriteInstance {},
	vigilanteMine: class extends self.ISpriteInstance {},
	officerAlt: class extends self.ISpriteInstance {},
	hoseNozzle: class extends self.ISpriteInstance {},
	waterProj: class extends self.ISpriteInstance {},
	waterProj2: class extends self.ISpriteInstance {},
	healthPotion: class extends self.ISpriteInstance {},
	smashArea3: class extends self.ISpriteInstance {},
	chef: class extends self.ISpriteInstance {},
	pan: class extends self.ISpriteInstance {},
	food: class extends self.ISpriteInstance {},
	food2: class extends self.ISpriteInstance {},
	chefFlare: class extends self.IParticlesInstance {},
	rpgHero: class extends self.ISpriteInstance {},
	rpgHeroSword: class extends self.ISpriteInstance {},
	upgradeIcon: class extends self.ISpriteInstance {},
	patriotGun: class extends self.ISpriteInstance {},
	patriot: class extends self.ISpriteInstance {},
	miniFirework: class extends self.ISpriteInstance {},
	miniFirework2: class extends self.ISpriteInstance {},
	megaFire: class extends self.ISpriteInstance {},
	spiritBusterAlt: class extends self.ISpriteInstance {},
	ghostGun2: class extends self.ISpriteInstance {},
	spiritWave: class extends self.ISpriteInstance {},
	spiritWave2: class extends self.ISpriteInstance {},
	slowArea: class extends self.ISpriteInstance {},
	ghostSlow: class extends self.ISpriteInstance {},
	elemental: class extends self.ISpriteInstance {},
	elementalOrb: class extends self.ISpriteInstance {},
	iceBullet: class extends self.ISpriteInstance {},
	fireBullet: class extends self.ISpriteInstance {},
	iceCube: class extends self.ISpriteInstance {},
	hivemind: class extends self.ISpriteInstance {},
	hiveMindGun: class extends self.ISpriteInstance {},
	hiveMindCore: class extends self.ISpriteInstance {},
	hiveMindChain: class extends self.ISpriteInstance {},
	swarmIndicator: class extends self.ISpriteInstance {},
	smashArea4: class extends self.ISpriteInstance {},
	weakenEffect: class extends self.ISpriteInstance {},
	fleetCommander: class extends self.ISpriteInstance {},
	captainGun: class extends self.ISpriteInstance {},
	starShot: class extends self.ISpriteInstance {},
	galaxyStrip: class extends self.I9PatchInstance {},
	galaxyStrip2: class extends self.ITiledBackgroundInstance {},
	speedZone: class extends self.ISpriteInstance {},
	speedZonePlace: class extends self.ISpriteInstance {},
	batter: class extends self.ISpriteInstance {},
	gun18: class extends self.ISpriteInstance {},
	baseball: class extends self.ISpriteInstance {},
	bat: class extends self.ISpriteInstance {},
	healingCandy2: class extends self.ISpriteInstance {},
	trooper: class extends self.ISpriteInstance {},
	trooperBlaster: class extends self.ISpriteInstance {},
	bullet14: class extends self.ISpriteInstance {},
	shockGrenade: class extends self.ISpriteInstance {},
	stunArea: class extends self.ISpriteInstance {},
	nebula: class extends self.ISpriteInstance {},
	galaxy: class extends self.ISpriteInstance {},
	galaxyBall: class extends self.ISpriteInstance {},
	speedZone2: class extends self.ISpriteInstance {},
	pumpkinBucket2: class extends self.ISpriteInstance {},
	trickOrTreaterAlt: class extends self.ISpriteInstance {},
	spiritPumpkin: class extends self.ISpriteInstance {},
	healingCandy3: class extends self.ISpriteInstance {},
	pumpkinSpawn: class extends self.ISpriteInstance {},
	hannyaAlt: class extends self.ISpriteInstance {},
	gun19: class extends self.ISpriteInstance {},
	hannyaAltSpear: class extends self.ISpriteInstance {},
	angelMeter: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	hannyaAltSpear2: class extends self.ISpriteInstance {},
	jimm: class extends self.ISpriteInstance {},
	stapler2: class extends self.ISpriteInstance {},
	staple2: class extends self.ISpriteInstance {},
	witch2: class extends self.ISpriteInstance {},
	broom2: class extends self.ISpriteInstance {},
	pumpkin2: class extends self.ISpriteInstance {},
	sumo: class extends self.ISpriteInstance {},
	sumoHand: class extends self.ISpriteInstance {},
	sushiRoll: class extends self.ISpriteInstance {},
	sushiMeter: class extends self.ISpriteInstance {},
	futurist: class extends self.ISpriteInstance {},
	furturistGun: class extends self.ISpriteInstance {},
	futuristLaser: class extends self.ISpriteInstance {},
	OrbitalDrone: class extends self.ISpriteInstance {},
	Satellite: class extends self.ISpriteInstance {},
	futuristLaser2: class extends self.ISpriteInstance {},
	experiment: class extends self.ISpriteInstance {},
	echoPistol: class extends self.ISpriteInstance {},
	echo: class extends self.ISpriteInstance {},
	echoSpawner: class extends self.ISpriteInstance {},
	energyMeter: class extends self.ISpriteInstance {},
	monolithSniperShot: class extends self.ITiledBackgroundInstance {},
	pathogen: class extends self.ISpriteInstance {},
	pathogenGun: class extends self.ISpriteInstance {},
	virusBall: class extends self.ISpriteInstance {},
	virusBall2: class extends self.ISpriteInstance {},
	pathogenVestige: class extends self.ISpriteInstance {},
	virusBall3: class extends self.ISpriteInstance {},
	galacticOutlaw: class extends self.ISpriteInstance {},
	singularityCapsule: class extends self.ISpriteInstance {},
	voidWave: class extends self.ISpriteInstance {},
	voidPortal: class extends self.ISpriteInstance {},
	cultist: class extends self.ISpriteInstance {},
	grimoir: class extends self.ISpriteInstance {},
	cursedVisage: class extends self.ISpriteInstance {},
	cursedVisage2: class extends self.ISpriteInstance {},
	sigil: class extends self.ISpriteInstance {},
	mothMan: class extends self.ISpriteInstance {},
	gun20: class extends self.ISpriteInstance {},
	moth: class extends self.ISpriteInstance {},
	mothBite: class extends self.ISpriteInstance {},
	lanternMeter: class extends self.ISpriteInstance {},
	mothLight: class extends self.ISpriteInstance {},
	hypnotizedEffect: class extends self.ISpriteInstance {},
	swampCreature: class extends self.ISpriteInstance {},
	mudHand: class extends self.ISpriteInstance {},
	mudBall: class extends self.ISpriteInstance {},
	mudBall2: class extends self.ISpriteInstance {},
	phantomKnight: class extends self.ISpriteInstance {},
	graveBuster: class extends self.ISpriteInstance {},
	cursedVisage3: class extends self.ISpriteInstance {},
	wendigo: class extends self.ISpriteInstance {},
	wendigoStaff: class extends self.ISpriteInstance {},
	boneShard: class extends self.ISpriteInstance {},
	curse: class extends self.ISpriteInstance {},
	boneShard2: class extends self.ISpriteInstance {},
	cursedVisage4: class extends self.ISpriteInstance {},
	yukiOnna: class extends self.ISpriteInstance {},
	gun21: class extends self.ISpriteInstance {},
	yukiOnnaNote: class extends self.ISpriteInstance {},
	yukiOnnaNote2: class extends self.ISpriteInstance {},
	superFreezeEffect: class extends self.ISpriteInstance {},
	freezeEffect: class extends self.ISpriteInstance {},
	bellGun: class extends self.ISpriteInstance {},
	vampireAlt: class extends self.ISpriteInstance {},
	batProjectile: class extends self.ISpriteInstance {},
	heal: class extends self.IParticlesInstance {},
	bloodBat: class extends self.ISpriteInstance {},
	marionette: class extends self.ISpriteInstance {},
	marionetteCross: class extends self.ISpriteInstance {},
	eyeball: class extends self.ISpriteInstance {},
	ring2: class extends self.ISpriteInstance {},
	babyHead: class extends self.ISpriteInstance {},
	string: class extends self.ITiledBackgroundInstance {},
	porcelainShard: class extends self.ISpriteInstance {},
	oni: class extends self.ISpriteInstance {},
	gun22: class extends self.ISpriteInstance {},
	bullet15: class extends self.ISpriteInstance {},
	oniClub: class extends self.ISpriteInstance {},
	executionerAxe5: class extends self.ISpriteInstance {},
	cursedVisage5: class extends self.ISpriteInstance {},
	cursedVisage6: class extends self.ISpriteInstance {},
	yeti: class extends self.ISpriteInstance {},
	iceCannon: class extends self.ISpriteInstance {},
	iceballProj: class extends self.ISpriteInstance {},
	icicle: class extends self.ISpriteInstance {},
	freezeArea: class extends self.ISpriteInstance {},
	freezeEffect2: class extends self.ISpriteInstance {},
	siren: class extends self.ISpriteInstance {},
	conch: class extends self.ISpriteInstance {},
	acidDrop: class extends self.ISpriteInstance {},
	poisonEffect: class extends self.ISpriteInstance {},
	poisonBar: class extends self.ISpriteInstance {},
	blowfish: class extends self.ISpriteInstance {},
	cloudPlatform: class extends self.ISpriteInstance {},
	healOrb: class extends self.ISpriteInstance {},
	galaxyTile: class extends self.I9PatchInstance {},
	frame: class extends self.ISpriteInstance {},
	mapMove: class extends self.ISpriteInstance {},
	levelController: class extends self.ISpriteInstance {},
	darkness: class extends self.ISpriteInstance {},
	eclipseMeter: class extends self.ISpriteInstance {},
	sandstorm: class extends self.IParticlesInstance {},
	shinobi: class extends self.ISpriteInstance {},
	kunaiHeld: class extends self.ISpriteInstance {},
	kunaiBullet: class extends self.ISpriteInstance {},
	shadowClone: class extends self.ISpriteInstance {},
	pop: class extends self.IParticlesInstance {},
	poisonGoblin2: class extends self.ISpriteInstance {},
	salaryMan: class extends self.ISpriteInstance {},
	phone: class extends self.ISpriteInstance {},
	speechBubble: class extends self.ISpriteInstance {},
	speechBubble2: class extends self.ISpriteInstance {},
	gun23: class extends self.ISpriteInstance {},
	bullet16: class extends self.ISpriteInstance {},
	idol: class extends self.ISpriteInstance {},
	microphone: class extends self.ISpriteInstance {},
	idolNote: class extends self.ISpriteInstance {},
	idolWave: class extends self.ISpriteInstance {},
	idolCharmRadius: class extends self.ISpriteInstance {},
	motivatedEffect: class extends self.ISpriteInstance {},
	delinquent: class extends self.ISpriteInstance {},
	gun24: class extends self.ISpriteInstance {},
	bullet17: class extends self.ISpriteInstance {},
	nailedBat: class extends self.ISpriteInstance {},
	hadesRadius2: class extends self.ISpriteInstance {},
	ora: class extends self.ISpriteInstance {},
	rageMeter: class extends self.ISpriteFontInstance {},
	ora2: class extends self.ISpriteInstance {},
	foodVendor: class extends self.ISpriteInstance {},
	skewer: class extends self.ISpriteInstance {},
	kebab: class extends self.ISpriteInstance {},
	engorged: class extends self.ISpriteInstance {},
	takoyaki: class extends self.ISpriteInstance {},
	sashimi: class extends self.ISpriteInstance {},
	mascot: class extends self.ISpriteInstance {},
	dinoPunch2: class extends self.ISpriteInstance {},
	pacify: class extends self.ISpriteInstance {},
	pacifyEffect: class extends self.ISpriteInstance {},
	bugCatcher: class extends self.ISpriteInstance {},
	bugNet: class extends self.ISpriteInstance {},
	beetleBullet: class extends self.ISpriteInstance {},
	bullet18: class extends self.ISpriteInstance {},
	priest: class extends self.ISpriteInstance {},
	purificationFlower: class extends self.ISpriteInstance {},
	charmMiko: class extends self.ISpriteInstance {},
	priestShieldSegment: class extends self.ISpriteInstance {},
	sumoWave: class extends self.ISpriteInstance {},
	karmaArea: class extends self.ISpriteInstance {},
	weighedEffect: class extends self.ISpriteInstance {},
	cherryTree: class extends self.ISpriteInstance {},
	cherryBranch: class extends self.ISpriteInstance {},
	flowerBall: class extends self.ISpriteInstance {},
	flowerPetal: class extends self.ISpriteInstance {},
	flowerBall2: class extends self.ISpriteInstance {},
	flowerBall3: class extends self.ISpriteInstance {},
	festivalMan: class extends self.ISpriteInstance {},
	festivalStick: class extends self.ISpriteInstance {},
	koiKite: class extends self.ISpriteInstance {},
	carpSpawner: class extends self.ISpriteInstance {},
	blessedBolt: class extends self.ISpriteInstance {},
	blessedPrism: class extends self.ISpriteInstance {},
	seraphim: class extends self.ISpriteInstance {},
	orbitMode: class extends self.ISpriteInstance {},
	martyr: class extends self.ISpriteInstance {},
	curvedKnife: class extends self.ISpriteInstance {},
	bloodyStab: class extends self.ISpriteInstance {},
	curse2: class extends self.ISpriteInstance {},
	spiritChains: class extends self.ITiledBackgroundInstance {},
	bleed: class extends self.IParticlesInstance {},
	players: class extends self.ISpriteInstance {},
	weapons: class extends self.ISpriteInstance {},
	projectiles: class extends self.ISpriteInstance {},
	bars: class extends self.ISpriteInstance {},
	melee: class extends self.ISpriteInstance {},
	shields: class extends self.ISpriteInstance {},
	builderObjects: class extends self.ISpriteInstance {}
}